apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app-1
  template:
    metadata:
      labels:
        app: flask-app-1
    spec:
      containers:
      - name: flask-app-1
        image: paulfatoki/f-app1.0:latest
        ports:
        - containerPort: 5002

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002
  type: LoadBalancer
